version: '2.1'

services:
  et-msg-handler:
    image: "hmctspublic.azurecr.io/et/msg-handler:latest"
    container_name: et-msg-handler
    ports:
      - 8085:8085
    environment:
      IDAM_API_URL: "http://idam-api:5000"
      IDAM_API_JWK_URL: "http://idam-api:5000/jwks"
      IDAM_API_OIDC_URL: "http://idam-api:5000/o/token"
      IDAM_CLIENT_REDIRECT_URL: "https://localhost:8085/oauth2redirect"
      SERVICE_AUTH_PROVIDER_URL: "http://service-auth-provider-api:8080"
      CCD_DATA_STORE_API_URL: "http://ccd-data-store-api:4452"
      MICRO_SERVICE: "et_msg_handler"
