java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    ET_MESSAGE_HANDLER_DB_CONN_OPTIONS: ""
    ET_MESSAGE_HANDLER_POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    ET_MESSAGE_HANDLER_POSTGRES_DATABASE: "{{ .Values.postgresql.postgresqlDatabase}}"
    ET_MESSAGE_HANDLER_POSTGRES_USER: "{{ .Values.postgresql.postgresqlUsername}}"
    ET_MESSAGE_HANDLER_POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
  keyVaults:
    et-shared:
      resourceGroup: et
      secrets:
        - et-message-handler-s2s-key
        - caseworker-user-name
        - caseworker-password
        - gov-notify-api-key
        - create-updates-queue-send-connection-string
        - create-updates-queue-listen-connection-string
        - update-case-queue-send-connection-string
        - update-case-queue-listen-connection-string
        - idam-client-secret
  postgresql:
    enabled: true
